### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by kouzhudong** [OpenVPN/tap-windows6#157]
E:\code\NetWork\OpenVPN\tap-windows6>C:\Python27\python.exe buildtap.py --sdk=WDK -b
***** BUILD TAP config
***** BUILD TAP arch=i386
('RUN:', 'msbuild.exe E:\\code\\NetWork\\OpenVPN\\tap-windows6\\src\\tap-windows6.vcxproj /p:Configuration=Release /p:Platform=Win32')
用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.11.2+f32259642
版权所有(C) Microsoft Corporation。保留所有权利。

生成启动时间为 2023/3/16 8:54:44。
节点 1 上的项目“E:\code\NetWork\OpenVPN\tap-windows6\src\tap-windows6.vcxproj”(默认目标)。
C:\Program Files (x86)\Windows Kits\10\build\WindowsDriver.common.targets(235,5): error :  'Win32' is not a valid architecture for Kernel mode drivers or UMDF drivers [E:\code\NetWork\OpenVPN\tap-windows6\src\tap-windows6.vcxpr
oj]
已完成生成项目“E:\code\NetWork\OpenVPN\tap-windows6\src\tap-windows6.vcxproj”(默认目标)的操作 - 失败。

生成失败。

“E:\code\NetWork\OpenVPN\tap-windows6\src\tap-windows6.vcxproj”(默认目标) (1) ->
(ValidateDriverProperties 目标) ->
  C:\Program Files (x86)\Windows Kits\10\build\WindowsDriver.common.targets(235,5): error :  'Win32' is not a valid architecture for Kernel mode drivers or UMDF drivers [E:\code\NetWork\OpenVPN\tap-windows6\src\tap-windows6.vcx
proj]

    0 个警告
    1 个错误

已用时间 00:00:00.17
***** BUILD TAP arch=amd64
('RUN:', 'msbuild.exe E:\\code\\NetWork\\OpenVPN\\tap-windows6\\src\\tap-windows6.vcxproj /p:Configuration=Release /p:Platform=x64')
用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.11.2+f32259642
版权所有(C) Microsoft Corporation。保留所有权利。

生成启动时间为 2023/3/16 8:54:45。
节点 1 上的项目“E:\code\NetWork\OpenVPN\tap-windows6\src\tap-windows6.vcxproj”(默认目标)。
C:\Program Files (x86)\Windows Kits\10\build\WindowsDriver.common.targets(238,5): error :  'Windows7' is not a supported OS Version [E:\code\NetWork\OpenVPN\tap-windows6\src\tap-windows6.vcxproj]
已完成生成项目“E:\code\NetWork\OpenVPN\tap-windows6\src\tap-windows6.vcxproj”(默认目标)的操作 - 失败。

生成失败。

“E:\code\NetWork\OpenVPN\tap-windows6\src\tap-windows6.vcxproj”(默认目标) (1) ->
(ValidateDriverProperties 目标) ->
  C:\Program Files (x86)\Windows Kits\10\build\WindowsDriver.common.targets(238,5): error :  'Windows7' is not a supported OS Version [E:\code\NetWork\OpenVPN\tap-windows6\src\tap-windows6.vcxproj]

    0 个警告
    1 个错误

已用时间 00:00:00.18
***** BUILD TAP arch=arm64
('RUN:', 'msbuild.exe E:\\code\\NetWork\\OpenVPN\\tap-windows6\\src\\tap-windows6.vcxproj /p:Configuration=Release /p:Platform=arm64')
用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.11.2+f32259642
版权所有(C) Microsoft Corporation。保留所有权利。

生成启动时间为 2023/3/16 8:54:45。
节点 1 上的项目“E:\code\NetWork\OpenVPN\tap-windows6\src\tap-windows6.vcxproj”(默认目标)。
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(820,5): error : The BaseOutputPath/OutputPath property is not set for project 'tap-windows6.vcxproj'.  P
lease check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Release'  Platform='arm64'.  You may be seeing this message because you are trying to build a
project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [E:\code\NetWork\OpenVPN\tap-windows6\src\tap-windows6.vcxproj]
已完成生成项目“E:\code\NetWork\OpenVPN\tap-windows6\src\tap-windows6.vcxproj”(默认目标)的操作 - 失败。

生成失败。

“E:\code\NetWork\OpenVPN\tap-windows6\src\tap-windows6.vcxproj”(默认目标) (1) ->
(_CheckForInvalidConfigurationAndPlatform 目标) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(820,5): error : The BaseOutputPath/OutputPath property is not set for project 'tap-windows6.vcxproj'.
 Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Release'  Platform='arm64'.  You may be seeing this message because you are trying to build
a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [E:\code\NetWork\OpenVPN\tap-windows6\src\tap-windows6.vcxproj]

    0 个警告
    1 个错误

已用时间 00:00:00.12
COPY E:\code\NetWork\OpenVPN\tap-windows6\src\tap-windows.h E:\code\NetWork\OpenVPN\tap-windows6\dist\include
***** Generated files
E:\code\NetWork\OpenVPN\tap-windows6\dist
E:\code\NetWork\OpenVPN\tap-windows6\dist\amd64
E:\code\NetWork\OpenVPN\tap-windows6\dist\arm64
E:\code\NetWork\OpenVPN\tap-windows6\dist\i386
E:\code\NetWork\OpenVPN\tap-windows6\dist\include
E:\code\NetWork\OpenVPN\tap-windows6\dist\include\tap-windows.h
('***** Generated tarball:', 'E:\\code\\NetWork\\OpenVPN\\tap-windows6\\tap6.tar.gz')

E:\code\NetWork\OpenVPN\tap-windows6>

**Comment by oblomingo** [comment]
It seems I've faced the same issue:
My command line: `buildtap.py --build --debug --clean --sdk=wdk`
Result:
`C:\Source\tap-windows6>buildtap.py --build --debug --clean --sdk=wdk
('RM', 'C:\\Source\\tap-windows6\\src\\config.h')
('RM', 'C:\\Source\\tap-windows6\\src\\OemVista.inf')
('RM', 'C:\\Source\\tap-windows6\\src\\tap-windows6.vcxproj')
('RMTREE', 'C:\\Source\\tap-windows6\\dist\\amd64')
('RMTREE', 'C:\\Source\\tap-windows6\\dist\\arm64')
('RMTREE', 'C:\\Source\\tap-windows6\\dist\\i386')
('RMTREE', 'C:\\Source\\tap-windows6\\dist\\include')
***** BUILD TAP config
***** BUILD TAP arch=i386
('RUN:', 'msbuild.exe C:\\Source\\tap-windows6\\src\\tap-windows6.vcxproj /p:Configuration=Debug /p:Platform=Win32')
MSBuild version 17.5.0+6f08c67f3 for .NET Framework
Build started 3/20/2023 12:36:05 PM.
Included response file: C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\MSBuild.rsp

Project "C:\Source\tap-windows6\src\tap-windows6.vcxproj" on node 1 (default targets).
C:\Program Files (x86)\Windows Kits\10\build\10.0.22621.0\WindowsDriver.common.targets(235,5): error :  'Win32' is not a valid architecture for Kernel mode drivers or UMDF drivers [C:\Source\tap-windows6\src\tap-windows6.vcxproj]
Done Building Project "C:\Source\tap-windows6\src\tap-windows6.vcxproj" (default targets) -- FAILED.


Build FAILED.

"C:\Source\tap-windows6\src\tap-windows6.vcxproj" (default target) (1) ->
(ValidateDriverProperties target) ->
  C:\Program Files (x86)\Windows Kits\10\build\10.0.22621.0\WindowsDriver.common.targets(235,5): error :  'Win32' is not a valid architecture for Kernel mode drivers or UMDF drivers [C:\Source\tap-windows6\src\tap-windows6.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.22
('MAKEDIRS', 'C:\\Source\\tap-windows6\\dist\\i386')
***** BUILD TAP arch=amd64
('RUN:', 'msbuild.exe C:\\Source\\tap-windows6\\src\\tap-windows6.vcxproj /p:Configuration=Debug /p:Platform=x64')
MSBuild version 17.5.0+6f08c67f3 for .NET Framework
Build started 3/20/2023 12:36:06 PM.
Included response file: C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\MSBuild.rsp

Project "C:\Source\tap-windows6\src\tap-windows6.vcxproj" on node 1 (default targets).
C:\Program Files (x86)\Windows Kits\10\build\10.0.22621.0\WindowsDriver.common.targets(238,5): error :  'Windows7' is not a supported OS Version [C:\Source\tap-windows6\src\tap-windows6.vcxproj]
Done Building Project "C:\Source\tap-windows6\src\tap-windows6.vcxproj" (default targets) -- FAILED.


Build FAILED.

"C:\Source\tap-windows6\src\tap-windows6.vcxproj" (default target) (1) ->
(ValidateDriverProperties target) ->
  C:\Program Files (x86)\Windows Kits\10\build\10.0.22621.0\WindowsDriver.common.targets(238,5): error :  'Windows7' is not a supported OS Version [C:\Source\tap-windows6\src\tap-windows6.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.23
('MAKEDIRS', 'C:\\Source\\tap-windows6\\dist\\amd64')
***** BUILD TAP arch=arm64
('RUN:', 'msbuild.exe C:\\Source\\tap-windows6\\src\\tap-windows6.vcxproj /p:Configuration=Debug /p:Platform=arm64')
MSBuild version 17.5.0+6f08c67f3 for .NET Framework
Build started 3/20/2023 12:36:06 PM.
Included response file: C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\MSBuild.rsp

Project "C:\Source\tap-windows6\src\tap-windows6.vcxproj" on node 1 (default targets).
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(832,5): error : The BaseOutputPath/OutputPath property is not set for project 'tap-windows6.vcxproj'.  Please che
ck to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='arm64'.  You may be seeing this message because you are trying to build a project without a s
olution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [C:\Source\tap-windows6\src\tap-windows6.vcxproj]
Done Building Project "C:\Source\tap-windows6\src\tap-windows6.vcxproj" (default targets) -- FAILED.


Build FAILED.

"C:\Source\tap-windows6\src\tap-windows6.vcxproj" (default target) (1) ->
(_CheckForInvalidConfigurationAndPlatform target) ->
  C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(832,5): error : The BaseOutputPath/OutputPath property is not set for project 'tap-windows6.vcxproj'.  Please c
heck to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='arm64'.  You may be seeing this message because you are trying to build a project without a
 solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [C:\Source\tap-windows6\src\tap-windows6.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.11
('MAKEDIRS', 'C:\\Source\\tap-windows6\\dist\\arm64')
('MAKEDIRS', 'C:\\Source\\tap-windows6\\dist\\include')
COPY C:\Source\tap-windows6\src\tap-windows.h C:\Source\tap-windows6\dist\include
***** Generated files
C:\Source\tap-windows6\dist
C:\Source\tap-windows6\dist\amd64
C:\Source\tap-windows6\dist\arm64
C:\Source\tap-windows6\dist\i386
C:\Source\tap-windows6\dist\include
C:\Source\tap-windows6\dist\include\tap-windows.h
('***** Generated tarball:', 'C:\\Source\\tap-windows6\\tap6.tar.gz')`

It seems that Windows Kits version 10.0.22621.0 has some validations that don't allow building the tap driver.

**Comment by lstipakov** [comment]
You need VS2019 and older WDK, for example [WDK for Windows 10, version 2004](https://go.microsoft.com/fwlink/?linkid=2128854).

**Comment by kouzhudong** [comment]
x64 Native Tools Command Prompt for VS 2022
+
WDK 10.0.22621.0

is the same error.

**Comment by lstipakov** [comment]
> x64 Native Tools Command Prompt for VS 2019 + WDK 10.0.19041.0 OK?

This should work.

**Comment by kouzhudong** [comment]
the error is : x64 Native Tools Command Prompt for VS 2019 + WDK 10.0.19041.0.

**Comment by lstipakov** [comment]
Can you provide the log from VS2019 + WDK 10.0.19041?

**Comment by kouzhudong** [comment]
where is log?

**Comment by kouzhudong** [comment]
![Uploading 1679379113332.png…]()

**Comment by kouzhudong** [comment]
![1679379113332](https://user-images.githubusercontent.com/18212165/226531150-cd4025fe-24ba-468a-9afc-502a8a72aa47.png)

**Comment by kouzhudong** [comment]
![1679379113332](https://user-images.githubusercontent.com/18212165/226531151-df8d81a9-7f47-4303-bf87-f0cc525d8330.png)

**Comment by kouzhudong** [comment]
![1679379113332](https://user-images.githubusercontent.com/18212165/226531149-7681e0e0-5e3c-491c-896c-a5dbe883551c.png)

**Comment by kouzhudong** [comment]
yes， have two WDK,
10.0.19041.0
10.0.22621.0

**Comment by lstipakov** [comment]
Looks like this is something with your build environment. I have attached log output from my build.
[build.log](https://github.com/OpenVPN/tap-windows6/files/11026264/build.log)

**Comment by kouzhudong** [comment]
23 个警告
    0 个错误

已用时间 00:00:11.56
COPY E:\code\NetWork\OpenVPN\tap-windows6\src\x64\Release\tap-windows6\OemVista.inf E:\code\NetWork\OpenVPN\tap-windows6\dist\amd64\OemVista.inf
COPY E:\code\NetWork\OpenVPN\tap-windows6\src\x64\Release\tap-windows6\tap0901.cat E:\code\NetWork\OpenVPN\tap-windows6\dist\amd64\tap0901.cat
COPY E:\code\NetWork\OpenVPN\tap-windows6\src\x64\Release\tap-windows6\tap0901.sys E:\code\NetWork\OpenVPN\tap-windows6\dist\amd64\tap0901.sys
COPY E:\code\NetWork\OpenVPN\tap-windows6\src\tap-windows.h E:\code\NetWork\OpenVPN\tap-windows6\dist\include
***** Generated files
E:\code\NetWork\OpenVPN\tap-windows6\dist
E:\code\NetWork\OpenVPN\tap-windows6\dist\amd64
E:\code\NetWork\OpenVPN\tap-windows6\dist\amd64\OemVista.inf
E:\code\NetWork\OpenVPN\tap-windows6\dist\amd64\tap0901.cat
E:\code\NetWork\OpenVPN\tap-windows6\dist\amd64\tap0901.sys
E:\code\NetWork\OpenVPN\tap-windows6\dist\i386
E:\code\NetWork\OpenVPN\tap-windows6\dist\i386\OemVista.inf
E:\code\NetWork\OpenVPN\tap-windows6\dist\i386\tap0901.cat
E:\code\NetWork\OpenVPN\tap-windows6\dist\i386\tap0901.sys
E:\code\NetWork\OpenVPN\tap-windows6\dist\include
E:\code\NetWork\OpenVPN\tap-windows6\dist\include\tap-windows.h
('***** Generated tarball:', 'E:\\code\\NetWork\\OpenVPN\\tap-windows6\\tap6.tar.gz')

E:\code\NetWork\OpenVPN\tap-windows6>
